# **1.2 - Elements of Linear Algebra**

### **1.2.0 - Python Libraries for Linear Algebra**

The Python libraries used in linear algebra for computational purposes are NumPy and SciPy.

In [75]:
import numpy as np
import sympy as sp

Using the arange function, we can make a column vector of numbers from $0$ to $n$ by calling $arange(n)$.

In [12]:
matrixA = np.arange(10)
print("A =", matrixA)

A = [0 1 2 3 4 5 6 7 8 9]


The zeros and ones function creates an array of $n$ elements containing only zeros and ones, respectively.

In [13]:
matrixA = np.zeros(10)
print("A =", matrixA)
matrixB = np.zeros(10)
print("B =", matrixB)
matrixC = np.zeros(10) + 10
print("C =", matrixC)

A = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
B = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
C = [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


The random numbers function rand(n) creates an array of 10 random numbers between 0 and 1.

In [15]:
matrixA = np.random.rand(10)
print("A =", matrixA)

A = [0.3792223  0.57268692 0.98527166 0.98650182 0.8196123  0.31626468
 0.45937137 0.24510413 0.89836489 0.9107593 ]


### **1.2.1 - Linear Spaces**

Let $U, V$ be vectors in $\mathbb{R}^m$.

##### Definition 1.2.1.1 - Linear Combination

A linear combination is the sum of all products of vectors multiplied by scalars. Formally, given vectors $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n \in V$ and scalars $c_1, c_2, \ldots, c_n \in \mathbb{R}$,
\begin{equation*}
    c_1\textbf{v}_1 + c_2\textbf{v}_2 + \cdots + c_n\textbf{v}_n
\end{equation*}
is a linear combination of the vectors $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n$.

##### Definition 1.2.1.2 - Linear Subspace

A linear subspace is a subset of vector spaces $U \subseteq V$ that is closed under vector addition and scalar multiplication. Namely, for all vectors $\textbf{u}_1, \textbf{u}_2 \in U$ and $\alpha \in \mathbb{R}$,
\begin{equation*}
    \textbf{u}_1 + \textbf{u}_2 \in U \text{ and } \alpha\textbf{u}_1 \in U
\end{equation*}
In particular, $\textbf{0}$ is always in a linear subspace.

##### Definition 1.2.1.3 - Span

Let $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n$ be vectors in a vector space $V$. The set of all linear combinations of $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n$ is called the span of $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n$, denoted by $\text{span}(\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n)$.

##### Lemma 1.2.1.4 - Every Span is a Linear Subspace

Let $W = \text{span}(\textbf{w}_1, \textbf{w}_2, \ldots, \textbf{w}_m)$, where $\textbf{w}_1, \textbf{w}_2, \ldots, \textbf{w}_m$ are vectors in a vector space. Then, $W$ is a linear subspace.

##### Definition 1.2.1.5 - Column Space and Row Space

Let $A \in \mathbb{R}^{m \times n}$ be an $m \times n$ matrix with column vectors $\textbf{a}_1, \textbf{a}_2, \ldots, \textbf{a}_m \in \mathbb{R}^n$. The column space of $A$, denoted as $\text{col}(A)$, is the span of the column vectors of $A$; that is, $\text{col}(A) = \text{span}(\textbf{a}_1, \textbf{a}_2, \ldots, \textbf{a}_m) \in \mathbb{R}^n$. The row space of $A$, denoted as $\text{row}(A)$, is the span of the row vectors of $A$; that is, $\text{row}(A) = \text{span}(\textbf{a}_1, \textbf{a}_2, \ldots, \textbf{a}_m) \in \mathbb{R}^m$.

##### Definition 1.2.1.6 - Linear Independence

A list of vectors $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n$ in a vector space $V$ are linearly independent if none of them can be written as a linear combination of the others; that is, for all $i \in \mathbb{Z}^+$,
\begin{equation*}
    \mathbf{v}_i \notin \text{span}(\{\mathbf{u}_j \ : \ i \neq j\})
\end{equation*}
Alternatively, a list of vectors $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n$ in a vector space $V$ are linearly independent if for scalars $c_1, c_2, \ldots, c_n \in \mathbb{R}$,
\begin{equation*}
    c_1\mathbf{v}_1 + c_2\mathbf{v}_2 + \cdots + c_n\mathbf{v}_n = \textbf{0}
\end{equation*}
implying that $c_1, c_2, \ldots, c_n = 0$.

##### Definition 1.2.1.7 - Linear Dependence

A list of vectors $\textbf{v}_1, \textbf{v}_2, \ldots, \textbf{v}_n$ in a vector space $V$ are linearly dependent if there exists scalars $c_1, c_2, \ldots, c_n \in \mathbb{R}$, not all zero, such that
\begin{equation*}
    c_1\mathbf{v}_1 + c_2\mathbf{v}_2 + \cdots + c_n\mathbf{v}_n = \textbf{0}
\end{equation*}
Equivalently, a list of vectors is linearly dependent if it is not linearly independent.

##### Lemma 1.2.1.8 - Determination of Scalars for Linear Independence/Depedence

The vectors $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ are linearly independent if and only if for all $i \in \mathbf{Z}$,
\begin{equation*}
    \sum_{i = 0}^n \alpha_i\mathbf{v}_i = \textbf{0} \to \alpha_i = 0
\end{equation*}
Equivalently, the vectors $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ are linearly dependent if and only if for all $i \in \mathbb{Z}$, there exists some $\alpha_i$, not all zero, such that
\begin{equation*}
    \sum_{i = 0}^n \alpha_i\mathbf{v}_i = 0
\end{equation*}

In [76]:
def Checking_Linear_Independence_or_Dependence(matrix, column):
    fulllinIndpTuple = tuple(np.arange(column))
    (rrefMatrix, linIndpCol) = sp.Matrix(matrix).T.rref()
    if linIndpCol == fulllinIndpTuple or column == 1:
        print("All columns of this matrix are linearly independent vectors.")
    else:
        print("Some columns of this matrix are linearly dependent vectors.")

print('Example 1')
matrixA = np.array([[1, -1, 2],[-2, 3, 1],[-1, 3, 8]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 2')
matrixA = np.array([[1, 1],[1, 2]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 3')
matrixA = np.array([[1, 2, 3]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 4')
matrixA = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 0]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 5')
matrixA = np.array([[1, 0, 1], [0, 1, 0]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 6')
matrixA = np.array([[1, 2, 4], [2, 1, 3], [4, -1, 1]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 7')
matrixA = np.array([[4, 2, 3], [2, 3, 1], [2, -5, 3]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 8')
matrixA = np.array([[1, -1, 2, 3], [-2, 3, 1, -2], [1, 0, 7, 7]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 9')
matrixA = np.array([[1, 2, 4], [2, 1, 3], [4, -1, 1]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 10')
matrixA = np.array([[2, 1],[3, 2]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 11')
matrixA = np.array([[2, 3],[4, 6]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 12')
matrixA = np.array([[-2, 1],[1, 3],[2, 4]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 13')
matrixA = np.array([[-1, 2],[1, -2],[2, -4]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 14')
matrixA = np.array([[1, 0, 0],[0, 1, 1],[1, 0, 1]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 15')
matrixA = np.array([[1, 0, 0],[0, 1, 1],[1, 0, 1],[1, 2, 3]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 16')
matrixA = np.array([[2, 1, -2], [3, 2, -2], [2, 2, 0]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 17')
matrixA = np.array([[2, 1, -2], [-2, -1, 2], [4, 2, -4]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 18')
matrixA = np.array([[1, 1, 3], [0, 2, 1]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 19')
matrixA = np.array([[7, -13, -19],[-1, 3, 1],[1, -1, -4]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 20')
matrixA = np.array([[8, -4, 3],[4, -1, 2],[12, -7, 9]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 21')
matrixA = np.array([[-2, 3, 3, -2],[0, 1, 0, -1],[1, -2, -2, 1],[-2, -3, 2, 3]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 22')
matrixA = np.array([[2, 2, 2],[3, 6, 0],[-4, -5, -3]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 23')
matrixA = np.array([[0, 0],[-7,3]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 24')
matrixA = np.array([[-2, 6]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 25')
matrixA = np.array([[-7, -4, -5],[8, 7, -3],[15, 11, 2]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 26')
matrixA = np.array([[1, 5],[-8, 1]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 27')
matrixA = np.array([[-8, 3, 0],[5, -2, 0],[6, 9, 0]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)
print('\nExample 28')
matrixA = np.array([[1, 4, 2, -1]])
(column, row) = matrixA.shape;
Checking_Linear_Independence_or_Dependence(matrixA, column)

Example 1
Some columns of this matrix are linearly dependent vectors.

Example 2
All columns of this matrix are linearly independent vectors.

Example 3
All columns of this matrix are linearly independent vectors.

Example 4
All columns of this matrix are linearly independent vectors.

Example 5
All columns of this matrix are linearly independent vectors.

Example 6
Some columns of this matrix are linearly dependent vectors.

Example 7
Some columns of this matrix are linearly dependent vectors.

Example 8
Some columns of this matrix are linearly dependent vectors.

Example 9
Some columns of this matrix are linearly dependent vectors.

Example 10
All columns of this matrix are linearly independent vectors.

Example 11
Some columns of this matrix are linearly dependent vectors.

Example 12
Some columns of this matrix are linearly dependent vectors.

Example 13
Some columns of this matrix are linearly dependent vectors.

Example 14
All columns of this matrix are linearly independent vecto

##### Definition 1.2.1.9 - Basis of a Vector Space

The vectors $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ form a basis for a vector space $V$ if and only if
- $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ are linearly independent
- $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ span $V$

##### Theorem 1.2.1.10 - Relationship Between Basis and Linear Dependence

If the vectors $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ span the vector space $V$, then any collection of $m$ vectors in $V$, where $m > n$, is linearly dependent.

##### Corollary 1.2.1.11

If both vectors $\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_m$ and $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ are bases for a vector space $V$, then $m = n$.

##### Definition 1.2.1.12 - Dimension of a Vector Space

Let $V$ be a vector space. If $V$ has a basis consisting of $n$ vectors, we say that $V$ has dimension $n$, denoted as $\text{div}(V) = n$. The subspace $\{\textbf{0}\}$ of $V$ is said to have dimension $n = 0$. $V$ is said to be finite dimensional is there is a finite set of vectors that spans $V$; otherwise, we say that $V$ is infinite dimensional.

##### Lemma 1.2.1.13 - Characterization of Linearly Dependent Sets

Let vectors $\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_m$ be a linearly dependent set of vectors with a subset of linearly independent vectors $\{\mathbf{u}_i \ : \ i \in \{1, 2, \ldots, m\}, \ k < m, \ k \in \mathbb{Z}\}$. Then, there exists an $i > k$ such that
- $\mathbf{u}_i \in \text{span}(\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_{i - 1})$
- $\text{span}(\{\mathbf{u}_j \ : \ j \in \{1, 2, \ldots, m\}\}) = \text{span}(\{\mathbf{u}_j \ : \ j \in \{1, 2, \ldots, m\}, \ i \neq j\})$

##### Theorem 1.2.1.14 - Properties of Dimension

If $V$ is a vector space of dimension $n > 0$, then
- any set of $n$ linearly independent vectors span $n$
- any $n$ vectors that span $V$ are linearly independent
- no set of fewer than $n$ vectors can span $V$
- any subset of fewer than $n$ linearly independent vectors can be extended to form a basis for $V$
- any spanning set containing more than $n$ vectors can be pared down to (reduced to) form a basis for $V$

### **1.2.2 - Orthogonality**

##### Definition 1.2.2.1 - Inner Product of Vectors

An inner product (dot product) on a vector space $V$ is an operation on $V$ that assigns, to each pair of vectors $\mathbf{u}$ and $\mathbf{v}$, satisfying the following conditions
- $\langle \mathbf{u}, \mathbf{u} \rangle \geq 0$ with equality if and only if $\mathbf{u} = \mathbf{0}$
- $\langle \mathbf{x}, \mathbf{y} \rangle = \langle \mathbf{y}, \mathbf{x} \rangle$ for all $\mathbf{x}, \mathbf{y} \in V$
- $\langle \alpha\mathbf{x} + \beta\mathbf{y}, \mathbf{z} \rangle = \langle \alpha\mathbf{x}, \mathbf{z} \rangle + \langle \beta\mathbf{y}, \mathbf{z} \rangle$ for all $\mathbf{x}, \mathbf{y}, \mathbf{z} \in V$ and all scalars $\alpha, \beta \in \mathbb{R}$

##### Definition 1.2.2.2 - Norm of a Vector

If vector $\mathbf{v}$ is in an inner product space $V$, then the norm (length) of $\mathbf{v}$ is
\begin{equation*}
    ||\mathbf{v}|| = \sqrt{\langle v, v \rangle} = \sqrt{\displaystyle\sum_{i = 1}^n \mathbf{v}_i^2}
\end{equation*}
If vectors $\mathbf{u}, \mathbf{v}$ are vectors in a normed linear space, the distance between $\mathbf{u}$ and $\mathbf{v}$ is $||\mathbf{v} - \mathbf{u}||$.

##### Definition 1.2.2.3 - Orthonormal Sets

A set of vectors $\{\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_m\}$ in a vectors space $V$ is orthonormal if for some $i, j$, where $i \neq j$, $\mathbf{v}_i, \mathbf{v}_j$ are pairwise orthogonal and vectors $\mathbf{v}_i, \mathbf{v}_j$ each have length 1; that is, $\langle \mathbf{v}_i, \mathbf{v}_j \rangle = 0$ and $||\mathbf{v}_i||, ||\mathbf{v}_j|| = 1$. Concisely, an orthonormal set of vectors is an orthogonal set of unit vectors.

##### Lemma 1.2.2.4 - Properties of Orthonormal Sets

Let $\{\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_m\}$ be an orthonormal set of vectors. Then,
- $\left|\left|\displaystyle\sum_{i = 1}^m \alpha_i\mathbf{v}_i\right|\right| = \displaystyle\sum_{i = 1}^m \alpha_i^2$ for any $\alpha_i \in \mathbb{R}$, $i \in \{1, 2, \ldots, m\}$
- $\{\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_m\}$ are linearly independent

##### Theorem 1.2.2.5 - Orthonormal Basis Expansion

Let $\{\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_n\}$ be an orthonormal basis for an inner product space $V$. If $\mathbf{v} = \displaystyle\sum_{i = 1}^n c_i\mathbf{u}_i$, then $c_i = \langle \mathbf{v}, \mathbf{u}_i \rangle$, or, alternatively,
\begin{equation*}
    \mathbf{v} = \displaystyle\sum_{i = 1}^n \langle \mathbf{v}, \mathbf{u}_i \rangle\mathbf{u}_i
\end{equation*}

##### Corollary 1.2.2.6

Let $\{\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_n\}$ be an orthonormal basis for an inner product space $V$. If $\mathbf{u} = \displaystyle\sum_{i = 1}^n a_i\mathbf{u}_i$ and $\mathbf{v} = \displaystyle\sum_{i = 1}^n b_i\mathbf{u}_i$, then
\begin{equation*}
    \langle \mathbf{u}, \mathbf{v} \rangle = \sum_{i = 1}^n a_ib_i
\end{equation*}

##### Corollary 1.2.2.7 - Parseval's Formula

If $\{\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_n\}$ is an orthonormal basis for an inner product space $V$ and $\mathbf{v} = \displaystyle\sum_{i = 1}^n c_i\mathbf{u}_i$, then
\begin{equation*}
    ||\mathbf{v}||^2 = \sum_{i = 1}^n c_i^2
\end{equation*}

##### Definition 1.2.2.8 - Orthogonal Projection

Let $U \subseteq V$ be a linear subspace of vector space $V$ with an orthonormal basis $\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_n$. The orthogonal projection of $\mathbf{v} \in V$ on $U$ is
\begin{equation*}
    \text{proj}_{U}V = \sum_{i = i}^n \langle \mathbf{v}, \mathbf{q}_i \rangle\mathbf{q}_i
\end{equation*}

##### Theorem 1.2.2.9 - Best Approximation Theorem

Let $U \subseteq V$ be a linear subspace with orthonormal basis $\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_n$. Let $\mathbf{v} \in V$. For any $\mathbf{u} \in U$,
\begin{equation*}
    ||\mathbf{v} - \text{proj}_{U}V|| \leq ||\mathbf{v} - \mathbf{u}||
\end{equation*}
Equality is achieved when $\mathbf{u} = \text{proj}_{U}V$.

##### Lemma 1.2.2.10 - Vector Form of the Pythagorean Theorem

Let $\mathbf{u}, \mathbf{v}$ be orthogonal vectors. Then, $||\mathbf{u} + \mathbf{v}||^2 = ||\mathbf{u}||^2 + ||\mathbf{v}||^2$.

##### Lemma 1.2.2.11 - Vector Form of the Cauchy-Schwarz Inequality

For any vectors $\mathbf{u}, \mathbf{v} \in V$, $|\langle \mathbf{u}, \mathbf{v} \rangle| \leq ||\mathbf{u}||||\mathbf{v}||$.

##### Lemma 1.2.2.12 - Orthogonal Decomposition

Let $U \subseteq V$ be a linear subspace with an orthonormal basis $\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_n$. Let $\mathbf{v} \in V$. For any $\mathbf{u} \in U$, $\langle \mathbf{v} - \text{proj}_{U}\mathbf{v}, \mathbf{u} \rangle = 0$. In particular, $\mathbf{v}$ can be decomposed as $(\mathbf{v} - \text{proj}_{U}\mathbf{v}) + \text{proj}_{U}\mathbf{v}$, where these two terms are orthogonal.

### **1.2.3 - Gram-Schmidt Orthogonalization Process**

##### Theorem 1.2.3.1 - Gram-Schmidt Process

Let $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n \in \mathbb{R}^n$ be linearly independent. Then, there exists an orthonormal basis $\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_n$ of $\text{span}(\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n)$. The process to determine this orthonormal basis is shown below.

Let $\{\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n\}$ be a basis for the inner product space $V$. Let
\begin{equation*}
    \mathbf{u}_1 = \frac{\mathbf{v}_1}{||\mathbf{v}_1||}
\end{equation*}
and define $\{\mathbf{v}_2, \ldots, \mathbf{v}_n\}$ recursively by
\begin{equation*}
    \mathbf{u}_{k + 1} = \frac{\mathbf{v}_{k + 1} - \mathbf{p}_k}{||\mathbf{v}_{k + 1} - \mathbf{p}_k||} \quad \text{ for } k = 1, 2, \cdots, n - 1
\end{equation*}
where
\begin{equation*}
    \mathbf{p}_k = \langle \mathbf{x}_{k + 1}, \mathbf{u}_1 \rangle\mathbf{u}_1 + \langle \mathbf{x}_{k + 1}, \mathbf{u}_2 \rangle\mathbf{u}_2 + \cdots + \langle \mathbf{x}_{k + 1}, \mathbf{u}_k \rangle\mathbf{u}_k
\end{equation*}
is the projection of $\mathbf{x}_{k + 1}$ onto $\text{span}(\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_n)$. Then, the set
\begin{equation*}
    \{\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_n\}
\end{equation*}
is an orthonormal basis for $V$.

In [41]:
def Gram_Schmidt_Orthogonalization_Process(matrixA):
    matrixQ = np.zeros_like(matrixA)
    columnNumber = 0
    for a in A.T:
        v = np.copy(a) # copy transpose of matrix A
        for index in range(0, columnNumber):
            v -= np.dot(np.dot(matrixQ[:, index].T, a), matrixQ[:, index]) 
        u = v / np.linalg.norm(v)  # normalized vector in orthonormal basis
        matrixQ[:, columnNumber] = u # add normalized vector to matrix Q
        columnNumber += 1
    matrixR = np.dot(matrixQ.T, matrixA) # generate matrix R from matrix A and matrix Q
    return (matrixQ, matrixR)

print('Example 1')
A = np.array([[1, -2, -1],[2, 0, 1],[2, -4, 2],[4, 0, 0]], dtype = float)
(Q, R) = Gram_Schmidt_Orthogonalization_Process(A)
print('Q =\n', Q)
print('R =\n', R)
print('A = Q x R =\n', np.dot(Q, R)) # verify A = Q x R
print('\nExample 2')
A = np.array([[1, -2, -2],[4, 3, 2],[1 , 2, 1]], dtype = float)
(Q, R) = Gram_Schmidt_Orthogonalization_Process(A)
print('Q =\n', Q)
print('R =\n', R)
print('A = Q x R =\n', np.dot(Q, R)) # verify A = Q x R
print('\nExample 3')
A = np.array([[-8, -4, -8],[6, 0, 3],[-7 , 1, 2]], dtype = float)
(Q, R) = Gram_Schmidt_Orthogonalization_Process(A)
print('Q =\n', Q)
print('R =\n', R)
print('A = Q x R =\n', np.dot(Q, R)) # verify A = Q x R
print('\nExample 4')
A = np.array([[1, 0, 1],[3, 1, 0]], dtype = float)
(Q, R) = Gram_Schmidt_Orthogonalization_Process(A)
print('Q =\n', Q)
print('R =\n', R)
print('A = Q x R =\n', np.dot(Q, R)) # verify A = Q x R
print('\nExample 5')
A = np.array([[-9, -6, -18],[11, -2, 36]], dtype = float)
(Q, R) = Gram_Schmidt_Orthogonalization_Process(A)
print('Q =\n', Q)
print('R =\n', R)
print('A = Q x R =\n', np.dot(Q, R)) # verify A = Q x R
print('\nExample 6')
A = np.array([[-4, -2, -4],[1, -4, 10],[5, 13, 2]], dtype = float)
(Q, R) = Gram_Schmidt_Orthogonalization_Process(A)
print('Q =\n', Q)
print('R =\n', R)
print('A = Q x R =\n', np.dot(Q, R)) # verify A = Q x R

Example 1
Q =
 [[ 0.2 -0.4 -0.8]
 [ 0.4  0.2  0.4]
 [ 0.4 -0.8  0.4]
 [ 0.8  0.4 -0.2]]
R =
 [[ 5. -2.  1.]
 [ 0.  4. -1.]
 [ 0.  0.  2.]]
A = Q x R =
 [[ 1. -2. -1.]
 [ 2.  0.  1.]
 [ 2. -4.  2.]
 [ 4. -0.  0.]]

Example 2
Q =
 [[ 0.2357 -0.8889 -0.3928]
 [ 0.9428  0.1111  0.3143]
 [ 0.2357  0.4444 -0.8642]]
R =
 [[ 4.2426  2.8284  1.6499]
 [-0.      3.      2.4444]
 [ 0.     -0.      0.55  ]]
A = Q x R =
 [[ 1. -2. -2.]
 [ 4.  3.  2.]
 [ 1.  2.  1.]]

Example 3
Q =
 [[-0.6554 -0.7427  0.1374]
 [ 0.4915 -0.2813  0.8242]
 [-0.5735  0.6077  0.5494]]
R =
 [[12.2066  2.0481  5.5708]
 [-0.      3.5785  6.3129]
 [ 0.      0.      2.4725]]
A = Q x R =
 [[-8. -4. -8.]
 [ 6.  0.  3.]
 [-7.  1.  2.]]

Example 4
Q =
 [[ 0.3162 -0.9487  0.3714]
 [ 0.9487  0.3162  0.9285]]
R =
 [[ 3.1623  0.9487  0.3162]
 [ 0.      0.3162 -0.9487]
 [ 3.1568  0.9285  0.3714]]
A = Q x R =
 [[2.1724 0.3448 1.1379]
 [5.931  1.8621 0.3448]]

Example 5
Q =
 [[-0.6332 -0.774  -0.8575]
 [ 0.774  -0.6332  0.5145]]
R =
 [[1

### **1.2.4 - Eigenvalues and Eigenvectors**

##### Definition 1.2.4.1 - Eigenvalues and Eigenvectors

Let $A \in \mathbb{R}^{d \times d}$ be a $d \times d$ square matrix. Then, $\lambda \in \mathbb{R}$ is an eigenvalue (characteristic value) of $A$ if there exists a nonzero vector $\mathbf{x} \neq \mathbf{0}$ such that
\begin{equation*}
    A\mathbf{x} = \lambda\mathbf{x}
\end{equation*}
The vector $\mathbf{x}$ is referred to as an eigenvector (characteristic vector) belonging to the eigenvalue $\lambda$.

##### Lemma 1.2.4.2 = Properties of Eigenvalues

Let $A \in \mathbb{R}^{d \times d}$ be a $d \times d$ square matrix and let $\lambda$ be a scalar. The following statements are equivalent.
- $\lambda$ is an eigenvalue of $A$
- $(A - \lambda I)\mathbf{x} = \textbf{0}$ has a nontrivial solution.
- the nullspace $N(A - \lambda I) \neq \{\textbf{0}\}$
- $A - \lambda I$ is singular
- $\text{det}(A - \lambda I) = 0$

##### Lemma 1.2.4.2 - Number of Eigenvalues

Let matrix $A \in \mathbb{R}^{d \times d}$, and let $\lambda_1, \lambda_2, \ldots, \lambda_n$ be distinct eigenvalues of $A$ with the corresponding nonzero eigenvectors $\mathbf{x}_1, \mathbf{x}_2, \ldots, \mathbf{x}_n$. Then, $\mathbf{x}_1, \mathbf{x}_2, \ldots, \mathbf{x}_n$ are linearly independent, and $n \leq q$; that is, $A \in \mathbb{R}^{d \times d}$ has at most $d$ distinct eigenvalues.

In [87]:
def Finding_Eigenvalues_and_Eigenvectors(matrix):
  (eigenvalues, eigenvectors) = np.linalg.eig(matrix)
  print('Eigenvalues:\n', eigenvalues)
  print('Eigenvectors:\n', eigenvectors)

print('Example 1')
matrixA = np.array([[4, -2], [1, 1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 2')
matrixA = np.array([[3, 2], [3, -2]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 3')
matrixA = np.array([[2, -3, 1], [1, -2, 1], [1, -3, 2]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 4')
matrixA = np.array([[1, 2],[-2, 1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 5')
matrixA = np.array([[5, -18],[1, -1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 6')
matrixA = np.array([[2, 1],[0, 3]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 7')
matrixA = np.array([[5, 3],[3, 2]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 8')
matrixA = np.array([[-1, -2],[6, 6]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 9')
matrixA = np.array([[3, 2], [4, 1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 10')
matrixA = np.array([[6, -4], [3, -1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 11')
matrixA = np.array([[3, -1],[1, 1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 12')
matrixA = np.array([[3, -8],[2, 3]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 13')
matrixA = np.array([[1, 1],[-2, 3]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 14')
matrixA = np.array([[0, 1, 0],[0, 0, 1],[0, 0, 0]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 15')
matrixA = np.array([[1, 1, 1],[0, 2, 1],[0, 0, 1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 16')
matrixA = np.array([[1, 2, 1],[0, 3, 1],[0, 5, -1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 17')
matrixA = np.array([[4, 5, -1],[1, 0, -1],[0, 1, -1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 18')
matrixA = np.array([[-2, 0, 11],[1, 0, -1],[0, 1, -1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 19')
matrixA = np.array([[2, 0, 0, 0],[0, 2, 0, 0],[0, 0, 3, 0],[0, 0, 0, 4]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 20')
matrixA = np.array([[3, 0, 0, 0],[4, 1, 0, 0],[0, 0, 2, 1],[0, 0, 0, 2]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 21')
matrixA = np.array([[[-1, 3, 0],[0, 4, 4],[-5, 4, 0]]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 22')
matrixA = np.array([[-5, -1],[1, -7]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 23')
matrixA = np.array([[-1, 0, 0, 0],[2, 1, -1, 1],[1, 3, 1, -3],[1, 3, -1, -1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 24')
matrixA = np.array([[2, 3, -2, 1],[-4, -5, 2, -1],[-3, -3, 1, -1],[0, 0, 0, 2]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 25')
matrixA = np.array([[4, -3, -2, 2],[2, -1, -2, -2],[3, -3, -1, 5],[0, 0, 0, -2]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 26')
matrixA = np.array([[5, 0, 0],[22, 3, 8],[-16, -4, -9]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 27')
matrixA = np.array([[0, 0, -4],[2, -2, -4],[1, 0, -4]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 28')
matrixA = np.array([[1, 1, 1],[1, 1, 1],[-1, -1, -1]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 29')
matrixA = np.array([[-4, 0, 4, -8],[-2, -2, 2, -6],[1, 0, -4, 4],[1, 0, -4, 4]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)
print('\nExample 30')
matrixA = np.array([[-7, 9],[9, 17]], dtype = float)
Finding_Eigenvalues_and_Eigenvectors(matrixA)

Example 1
Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.8944 0.7071]
 [0.4472 0.7071]]

Example 2
Eigenvalues:
 [ 4. -3.]
Eigenvectors:
 [[ 0.8944 -0.3162]
 [ 0.4472  0.9487]]

Example 3
Eigenvalues:
 [0.+0.j 1.+0.j 1.-0.j]
Eigenvectors:
 [[0.5774+0.j     0.8495+0.j     0.8495-0.j    ]
 [0.5774+0.j     0.3419-0.1142j 0.3419+0.1142j]
 [0.5774+0.j     0.1762-0.3427j 0.1762+0.3427j]]

Example 4
Eigenvalues:
 [1.+2.j 1.-2.j]
Eigenvectors:
 [[0.    -0.7071j 0.    +0.7071j]
 [0.7071+0.j     0.7071-0.j    ]]

Example 5
Eigenvalues:
 [2.+3.j 2.-3.j]
Eigenvectors:
 [[0.9733+0.j     0.9733-0.j    ]
 [0.1622-0.1622j 0.1622+0.1622j]]

Example 6
Eigenvalues:
 [2. 3.]
Eigenvectors:
 [[1.     0.7071]
 [0.     0.7071]]

Example 7
Eigenvalues:
 [6.8541 0.1459]
Eigenvectors:
 [[ 0.8507 -0.5257]
 [ 0.5257  0.8507]]

Example 8
Eigenvalues:
 [2. 3.]
Eigenvectors:
 [[-0.5547  0.4472]
 [ 0.8321 -0.8944]]

Example 9
Eigenvalues:
 [ 5. -1.]
Eigenvectors:
 [[ 0.7071 -0.4472]
 [ 0.7071  0.8944]]

Example 10
Eigenvalu

##### Lemma 1.2.4.3 - Diagonalization and Similar Matrices

Let $A$ be similar to a matrix $D = \text{diag}(\lambda_1, \lambda_2, \ldots, \lambda_n)$ with distinct diagonal entries; that is, there exists a nonsingular matrix $P$ such that
\begin{equation*}
    A = PDP^{-1}
\end{equation*}
Let $\mathbf{p}_1, \mathbf{p}_2, \ldots, \mathbf{p}_d$ be the columns of $P$. Then,
\begin{equation*}
    AP = PD
\end{equation*}
which implies that
\begin{equation*}
    A\mathbf{p}_i = \lambda_i\mathbf{p}_i
\end{equation*}
for some $i \in \{1, 2, \ldots, d\}$.

##### Theorem 1.2.4.4 - Relationship Between Symmetric Matrices and Eigenvalues and Eigenvectors

If $A$ is a symmetric matrix, then any two eigenvectors from different eigenspaces are orthogonal.

##### Theorem 1.2.4.5 - The Spectral Theorem for Symmetric Matrices

An $n \times n$ symmetric matrix $A$ has the following properties.
- $A$ has $n$ real eigenvalues, counting multiplicities.
- If $\lambda$ is an eigenvalue of $A$ with multiplicity $k$, then the eigenspace for $\lambda$ is $k$-dimensional.
- The eigenspaces are mutually orthogonal; eigenvectors corresponding to different eigenvalues are orthogonal.
- $A$ is orthogonally diagonalizable.

##### Theorem 1.2.4.6 - Constrained Optimization

Let $A$ be $n \times n$ symmetric matrix $A$ with an orthogonal diagonalization $A = PDP^{-1}$. The columns of $P$ are orthonormal eigenvectors $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$ of $A$. Suppose that the diagonal of matrix $D$ are arranged so that $\lambda_1 \leq \lambda_2 \leq \cdots \leq \lambda_n$. Then,
\begin{equation*}
    \min_{x \neq 0} \frac{\mathbf{x}^TA\mathbf{x}}{\mathbf{x}^T\mathbf{x}} = \lambda_1
\end{equation*}
is achieved when $\mathbf{x} = \mathbf{v}_1$ and
\begin{equation*}
    \max_{x \neq 0} \frac{\mathbf{x}^TA\mathbf{x}}{\mathbf{x}^T\mathbf{x}} = \lambda_n
\end{equation*}
is achieved when $\mathbf{x} = \mathbf{v}_n$.

### **1.2.5 - References**

1. MAT 494 Chapter 1 Lecture 1 Notes
2. Steven J. Leon, Linear Algebra with Applications, 9th Edition