<a href="https://colab.research.google.com/github/ttruong1000/MAT-494-Mathematical-Methods-for-Data-Science/blob/main/1_4_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.4 - Principal Component Analysis**

### **1.4.0 - Python Libraries for Principal Component Analysis**

The Python libraries used in linear algebra for computational purposes are NumPy and SciPy.

In [7]:
import numpy as np
import sympy as sp

### **1.4.1 - Singular Value Decomposition**

##### Theorem 1.4.1.1 - The Singular Value Decomposition (SVD) Theorem

If $A$ is an $m \times n$ matrix, then $A$ has a singular value decomposition.

##### Theorem 1.4.1.2 - Dimension of Matrices in SVD

If an $m \times n$ matrix $A$ has $R$ nonzero singular values $\sigma_1, \sigma_2, \ldots, \sigma_r \geq 0$ with $\sigma_{r + 1}, \sigma_{r + 2}, \ldots, \sigma_n = 0$, then the dimension of the column space of $A$ $\text{col}(A) = r$.

Theorem 1.4.1.3 - The Singular Value Decomposition (SVD)

Let $A$ be an $m \times n$ matrix with the dimension of $\text{col}(A) = r$. THen, there exists an $m \times n$ matrix $\sum$, where the diagonal entries in $D$ are the first $r$ singular values of $A$ with $\sigma_1 \geq \sigma_2 \geq \cdots \geq \sigma_r \geq 0$, and there exists an $m \times m$ orthogonal matrix $U$ and an $n \times n$ orthogonal matrix $V$ such that
\begin{equation*}
  A = U\sum V^T
\end{equation*}
Any factorization $A = U\sum V^T$ with $U, V$ orthogonal and $\sum$ is called a singular value decomposition SVD of $A$. The matrices $U, V$ are not unique, but the diagonal entries of $\sum$ are unique and are necessarily the singular values of $A$. The columns of $U$ are called left singular vectors of $A$ and the columns of $V$ are called the right singular vectors of $A$.

Lemma 1.4.1.4 - Observations of Matrices in SVD

Let $A$ be an $m \times n$ matrix with a singular value decomposition $U\sum V^T$.
- The singular values $\sigma_1, \sigma_2, \ldots, \sigma_n$ of $A$ are unique; however, the matrices $U$ and $V$ are not unique.
- Since $V$ diagonalizes $A^TA$, it follows that the $\mathbf{v}_j$'s are eigenvectors of $A^TA$.
- Since $AA^T = U\sum\sum^TU^T$, it follows that $U$ diagonalizes $AA^T$ and that the $\mathbf{u}_j$'s are eigenvectors of $AA^T$.
- Comparing the $j$-th columns of each side of the euqation
\begin{equation*}
  AV = U\sum
\end{equation*}
we get
\begin{equation*}
  A\mathbf{v}_j = \sigma_j\mathbf{u}_j \quad j = 1, 2, \ldots, n
\end{equation*}
Similarly,
\begin{equation*}
  A^TU = V\left(\sum\right)^T
\end{equation*}
and hence
\begin{equation*}
  A\mathbf{u}_j = \sigma_j\mathbf{v}_j \quad j = 1, 2, \ldots, n
\end{equation*}
\begin{equation*}
  A\mathbf{u}_j = 0 \quad \text{ for } j = n + 1, n + 2, \ldots, m
\end{equation*}
The $\mathbf{v}_j$'s are called the right singular vectors of $A$, and the $\mathbf{u}_j$'s are called the left singular vectors of $A$.
- If $A$ has rank $r$, then
  - $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_r$ form an orthonormal basis for the row space of $A^T$ $R(A^T)$.
  - $\mathbf{v}_{r + 1}, \mathbf{v}_{r + 2}2, \ldots, \mathbf{v}_n$ form an orthonormal basis for the null space of $A$ $N(A)$.
  - $\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_r$ form an orthonormal basis for the row space of $A$ $R(A)$.
  - $\mathbf{u}_{r + 1}, \mathbf{u}_{r + 2}, \ldots, \mathbf{u}_n$ form an orthonormal basis for the null space of $A^T$ $N(A^T)$.
- The rank of the matrix $A$ is equal to the number of its nonzero signular values,w here singular values are counted according to multiplicity.
- In the case that $A$ has rank $r < n$, if we set
\begin{equation*}
  U_1 = (\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_r) \quad V_1 = (\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_r)
\end{equation*}
and define $\sum_1$ as an $r \times r$ matrix with nonzero diagonal entries $\sigma_1, \sigma_2, \ldots, \sigma_r$. Then, $A = U_1\sum_1V_1^T$, which is the compact form of the singular value decomposition of $A$.

In [6]:
print('Example 1')
A = [[1, 1],[1, 1],[0, 0]]
U, Sigma, V = np.linalg.svd(A)
print('U =\n', U)
print('Sigma =\n', Sigma)
print('V =\n', V)
print('\nExample 2')
A = [[1, 1],[2, 2]]
U, Sigma, V = np.linalg.svd(A)
print('U =\n', U)
print('Sigma =\n', Sigma)
print('V =\n', V)
print('\nExample 3')
A = [[2, -2],[1, 2]]
U, Sigma, V = np.linalg.svd(A)
print('U =\n', U)
print('Sigma =\n', Sigma)
print('V =\n', V)
print('\nExample 4')
A = [[1, 3],[3, 1],[0, 0],[0, 0]]
U, Sigma, V = np.linalg.svd(A)
print('U =\n', U)
print('Sigma =\n', Sigma)
print('V =\n', V)
print('\nExample 5')
A = [[2, 0, 0],[0, 2, 1],[0, 1, 2],[0, 0, 0]]
U, Sigma, V = np.linalg.svd(A)
print('U =\n', U)
print('Sigma =\n', Sigma)
print('V =\n', V)
print('\nExample 6')
A = [[-2, 8, 20],[14, 19, 10],[2, -2, 1]]
U, Sigma, V = np.linalg.svd(A)
print('U =\n', U)
print('Sigma =\n', Sigma)
print('V =\n', V)
print('\nExample 7')
A = [[2, 5, 4],[6, 3, 0],[6, 3, 0],[2, 5, 4]]
U, Sigma, V = np.linalg.svd(A)
print('U =\n', U)
print('Sigma =\n', Sigma)
print('V =\n', V)

Example 1
U =
 [[-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Sigma =
 [2. 0.]
V =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Example 2
U =
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
Sigma =
 [3.16227766e+00 1.57009246e-16]
V =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Example 3
U =
 [[-0.89442719  0.4472136 ]
 [ 0.4472136   0.89442719]]
Sigma =
 [3. 2.]
V =
 [[-0.4472136   0.89442719]
 [ 0.89442719  0.4472136 ]]

Example 4
U =
 [[-0.70710678 -0.70710678  0.          0.        ]
 [-0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
Sigma =
 [4. 2.]
V =
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]

Example 5
U =
 [[ 0.          1.          0.          0.        ]
 [-0.70710678  0.         -0.70710678  0.        ]
 [-0.70710678  0.          0.70710678  0.        ]
 [ 

### **1.4.2 - Low-Rank Matrix Approximation**

Definition 1.4.2.1 - Induced Norm

The 2-norm of a matrix $A \in \mathbb{R}_{m \times n}$ is
\begin{equation*}
  ||A||_2 = \max_{\textbf{0} \neq \mathbf{x} \in \mathbf{R}^m} \frac{||A\mathbf{x}||}{||\mathbf{x}||} = \max_{\mathbf{x} \neq 0, ||\mathbf{x}|| = 1} ||A\mathbf{x}|| = \max_{\mathbf{x} \neq 0, ||\mathbf{x}|| = 1} \mathbf{x}^TA^TA\mathbf{x}
\end{equation*}


##### Theorem 1.4.2.2 - Rank of a SVD Matrix

Let $A \in \mathbb{R}^{m \times n}$ matrix with SVD
\begin{equation*}
  A = \sum_{j = 1}^r \sigma_j\mathbf{u}_j\mathbf{v}_j^T
\end{equation*}
For $k < r$, truncate the sum at the $k$-th term
\begin{equation*}
  A_k = \sum_{j = 1}^k \sigma_j\mathbf{u}_j\mathbf{v}_j^T
\end{equation*}
The rank of $A_k$ is $\text{rank}(A_k) = k$. By construction,
- the vectors $\{\mathbf{u}_j \ | \ j = 1, 2, \ldots, k\}$ are orthonormal
- since $\sigma_j > 0$ for $j = 1, 2, \ldots, k$, and the vectors $\{\mathbf{u}_j \ | \ j = 1, 2, \ldots, k\}$ are orthonormal, $\{\mathbf{u}_j \ | \ j = 1, 2, \ldots, k\}$ spans the column space of $A_k$.


##### Lemma 1.4.2.3 - Matrix Norms and Singular Values

Let $A \in \mathbb{R}^{m \times n}$ be a matrix with SVD
\begin{equation*}
  A = \sum_{j = 1}^r \sigma_j\mathbf{u}_j\mathbf{v}_j^T
\end{equation*}
where $\sigma_1 \geq \sigma_2 \geq \cdots \geq \sigma_r > 0$ and let $A_k$ be the truncation
\begin{equation*}
  A_k = \sum_{j = 1}^k \sigma_j\mathbf{u}_j\mathbf{v}_j^T
\end{equation*}
Then,
\begin{equation*}
  ||A - A_k||_2^2 = \sigma_{k + 1}^2
\end{equation*}

##### Theorem 1.4.2.4 - Eckart-Young-Mirsky Theorem (Low-Pank Approximation in the Induced Norm)

Let $A \in \mathbb{R}^{m \times n}$ be a matrix with SVD
\begin{equation*}
  A = \sum_{j = 1}^r \sigma_j\mathbf{u}_j\mathbf{v}_j^T
\end{equation*}
Let $A_k$ be the truncation
\begin{equation*}
  A_k = \sum_{j = 1}^k \sigma_j\mathbf{u}_j\mathbf{v}_j^T
\end{equation*}
with $k < r$. Then, for any matrix $B \in \mathbb{R}^{m \times n}$ of rank at most $k$,
\begin{equation*}
  ||A - A_k|_2 \leq ||A - B||_2
\end{equation*}

### **1.4.3 - Principal Component Analysis**

##### Definition 1.4.3.1 - Sample Mean The Mean-Deviation Matrix

Let $[\mathbf{X}_1, \mathbf{X}_2, \ldots, \mathbf{X}_n]$ be a $p \times N$ matrix of observation. Then, the sample mean $M$ of the observation vectors $\mathbf{X}_1, \mathbf{X}_2, \ldots, \mathbf{X}_n$ is
\begin{equation*}
  \mathbf{M} = \frac{1}{N}(\mathbf{X}_1 + \mathbf{X}_2 + \ldots + \mathbf{X}_n)
\end{equation*}
Let the mean-deviation matrix $B$ be
\begin{equation*}
  B = [\hat{\mathbf{X}}_1, \hat{\mathbf{X}}_2, \ldots, \hat{\mathbf{X}}_n]
\end{equation*}
where $\hat{\mathbf{X}}_k = \mathbf{X}_k - \mathbf{M}$ for all $k = 1, 2, \ldots, N$. The mean-deviation matrix $B$ has a sample mean of zero.

##### Definition 1.4.3.2 - The Covariance Matrix

The (sample) covariance matrix is the $p \times p$ matrix $S$ such that
\begin{equation*}
  S = \frac{1}{N - 1}BB^T
\end{equation*}
where $B$ is the $p \times N$ mean-deviation matrix and $N$ is the number of vectors in $B$.

##### Definition 1.4.3.3 - Principal Component Analysis (PCA)

Let $B$ be the $p \times N$ mean-deviation matrix. Principal Component Analysis (PCA) is a method that finds the first $k$ orthonormal vectors $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$, where $k \leq p$, such that the objective function
\begin{equation*}
  \frac{1}{N}\sum_{i = 1}^N \sum_{j = 1}^N \langle \mathbf{X}_i, \mathbf{v}_j \rangle^2
\end{equation*}
is maximized, where $\langle \mathbf{X}_i, \mathbf{v}_j \rangle$ is the length of the projection of $\mathbf{X}_i$ to $\mathbf{v}_j$.

##### Definition 1.4.3.4 - Variance and Total Variance

Let $B$ be the $p \times N$ mean-deviation matrix and let $S$ be the covariance matrix. For each $j = 1, 2, \ldots, N$ in $\mathbf{X}_j$ of $S$, the diagonal entries of the covariance matrix $S$ are the variances of each $\mathbf{X}_j$. This variance measures the spread of the values of $\mathbf{X}_j$. The total variance of the data is the sum of the variances on the diagonal of $S$. Alternatively, the total variance can be written as
\begin{equation*}
  \text{Total Variance} = \text{tr}(S)
\end{equation*}
where $\text{tr}(S)$ is the trace of matrix $S$, the function that takes the sum of the diagonals of a square matrix $S$.

##### Definition 1.4.3.5 - Fraction of Variances in Principal Component Analysis

The fraction of the variances of the first $k$-term truncation under Principal Component Analysis is
\begin{equation*}
  \frac{\sum_{j = 1}^k \lambda_j}{\sum_{j = 1}^p \lambda_j}
\end{equation*}
where $\lambda_j$ are the eigenvalues of the singular value decompostion (SVD) of $S$.

### **1.4.4 - References**

1. MAT 494 Chapter 1 Lecture 1 Notes
2. Steven J. Leon, Linear Algebra with Applications, 9th Edition